<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Магазины");
?><div class="breadcrumbs">
	<div class="small-container breadcrumbs__inner">
		<div class="breadcrumbs__cell">
			 <?$APPLICATION->IncludeComponent(
	"bitrix:breadcrumb",
	"navcase",
	Array(
		"PATH" => "",
		"SITE_ID" => "s1",
		"START_FROM" => "0"
	)
);?>
		</div>
	</div>
</div>
<div class="column-container">
	<div class="column-container__left">
		 <?$APPLICATION->IncludeComponent(
	"bitrix:menu",
	"leftcatnews",
	Array(
		"ALLOW_MULTI_SELECT" => "N",
		"CHILD_MENU_TYPE" => "left",
		"COMPONENT_TEMPLATE" => "leftcatnews",
		"DELAY" => "N",
		"MAX_LEVEL" => "1",
		"MENU_CACHE_GET_VARS" => array(),
		"MENU_CACHE_TIME" => "3600",
		"MENU_CACHE_TYPE" => "N",
		"MENU_CACHE_USE_GROUPS" => "Y",
		"MENU_THEME" => "site",
		"ROOT_MENU_TYPE" => "leftshopsmenu",
		"USE_EXT" => "N"
	)
);?>
	</div>
	<div class="column-container__right">
		 <?if($_GET["m"] == FALSE):?>
		<h1 class="page-title">Магазины в Барнауле</h1>
		 <?$APPLICATION->IncludeComponent(
	"bitrix:map.yandex.view", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"CONTROLS" => array(
			0 => "ZOOM",
			1 => "MINIMAP",
			2 => "TYPECONTROL",
			3 => "SCALELINE",
		),
		"INIT_MAP_TYPE" => "MAP",
		"MAP_DATA" => "a:4:{s:10:\"yandex_lat\";d:53.35650978417144;s:10:\"yandex_lon\";d:83.70950005990399;s:12:\"yandex_scale\";i:12;s:10:\"PLACEMARKS\";a:10:{i:0;a:3:{s:3:\"LON\";d:83.719844101852;s:3:\"LAT\";d:53.385892405345;s:4:\"TEXT\";s:54:\"Силуэт###RN###пр-т Космонавтов, 41\";}i:1;a:3:{s:3:\"LON\";d:83.772736743075;s:3:\"LAT\";d:53.350297207746;s:4:\"TEXT\";s:59:\"Силуэт###RN###ул. Союза Республик, 44\";}i:2;a:3:{s:3:\"LON\";d:83.748697617297;s:3:\"LAT\";d:53.341996361298;s:4:\"TEXT\";s:68:\"ТРЦ «GALAXY»###RN###пр-т Строителей, 117 (1 эт.)\";}i:3;a:3:{s:3:\"LON\";d:83.636400736473;s:3:\"LAT\";d:53.350153505364;s:4:\"TEXT\";s:71:\"ТРЦ «ARENA»###RN###Павловский тракт, 188 (1 эт.) \";}i:4;a:3:{s:3:\"LON\";d:83.682696609021;s:3:\"LAT\";d:53.342204223445;s:4:\"TEXT\";s:79:\"ТРЦ «ЕВРОПА»###RN###Павловский тракт, 251в (1 эт.)\";}i:5;a:3:{s:3:\"LON\";d:83.775785628138;s:3:\"LAT\";d:53.335252042881;s:4:\"TEXT\";s:112:\"ТРЦ «СИТИ-центр»###RN###пр-т Красноармейский, 47а (этаж «Бахетле»)\";}i:6;a:3:{s:3:\"LON\";d:83.697351369039;s:3:\"LAT\";d:53.356699514045;s:4:\"TEXT\";s:67:\"ТРЦ «ВЕСНА»###RN###ул. Малахова, 86в (1 эт.)\";}i:7;a:3:{s:3:\"LON\";d:83.67574673502;s:3:\"LAT\";d:53.367384492106;s:4:\"TEXT\";s:55:\"ТЦ «БУМ»###RN###ул. Попова, 86 (1 эт.)\";}i:8;a:3:{s:3:\"LON\";d:83.7311458539;s:3:\"LAT\";d:53.389589467224;s:4:\"TEXT\";s:72:\"ТЦ «АЛТАЙ»###RN###пр-т Космонавтов, 6в (1 эт.)\";}i:9;a:3:{s:3:\"LON\";d:83.796631480867;s:3:\"LAT\";d:53.330226386168;s:4:\"TEXT\";s:64:\"ТД «ПАССАЖ»###RN###пр-т Ленина, 2б (1 эт.)\";}}}",
		"MAP_HEIGHT" => "490",
		"MAP_ID" => "",
		"MAP_WIDTH" => "100%",
		"OPTIONS" => array(
			0 => "ENABLE_SCROLL_ZOOM",
			1 => "ENABLE_DBLCLICK_ZOOM",
			2 => "ENABLE_DRAGGING",
		)
	),
	false
);?>
             <h2 class="page-sub-title">Профессиональные отделы</h2>
		 <?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"shops", 
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "6",
		"IBLOCK_TYPE" => "shops",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "10",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "shops"
	),
	false
);?>
             <h2 class="page-sub-title">Розничные отделы</h2>
             <?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"shops", 
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "6",
		"IBLOCK_TYPE" => "shops",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "11",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "shops"
	),
	false
);?>
<h2 class="page-sub-title">Магазины-салоны by Siluet</h2>
             <?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"shops", 
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "6",
		"IBLOCK_TYPE" => "shops",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "27",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "shops"
	),
	false
);?>
		 <?elseif($_GET["m"] == bis):?><br>
		<h1 class="page-title">Магазины в Бийске</h1>
             <?$APPLICATION->IncludeComponent(
	"bitrix:map.yandex.view", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"CONTROLS" => array(
			0 => "ZOOM",
			1 => "MINIMAP",
			2 => "TYPECONTROL",
			3 => "SCALELINE",
		),
		"INIT_MAP_TYPE" => "MAP",
		"MAP_DATA" => "a:4:{s:10:\"yandex_lat\";d:52.539296999999095;s:10:\"yandex_lon\";d:85.19390728027338;s:12:\"yandex_scale\";i:12;s:10:\"PLACEMARKS\";a:2:{i:0;a:3:{s:3:\"LON\";d:85.215561865749;s:3:\"LAT\";d:52.543324907224;s:4:\"TEXT\";s:99:\"ТРК «ВОСКРЕСЕНЬЕ»###RN###ул. И. Мухачева, 200 (цокольный эт.)\";}i:1;a:3:{s:3:\"LON\";d:85.125444956143;s:3:\"LAT\";d:52.51916936856;s:4:\"TEXT\";s:64:\"Силуэт###RN###ул. Социалистическая, 23/3\";}}}",
		"MAP_HEIGHT" => "490",
		"MAP_ID" => "",
		"MAP_WIDTH" => "100%",
		"OPTIONS" => array(
			0 => "ENABLE_SCROLL_ZOOM",
			1 => "ENABLE_DBLCLICK_ZOOM",
			2 => "ENABLE_DRAGGING",
		)
	),
	false
);?>
             <h2 class="page-sub-title">Профессиональные отделы</h2>
             <?$APPLICATION->IncludeComponent(
                 "bitrix:news.list",
                 "shops",
                 array(
                     "ACTIVE_DATE_FORMAT" => "d.m.Y",
                     "ADD_SECTIONS_CHAIN" => "N",
                     "AJAX_MODE" => "N",
                     "AJAX_OPTION_ADDITIONAL" => "",
                     "AJAX_OPTION_HISTORY" => "N",
                     "AJAX_OPTION_JUMP" => "N",
                     "AJAX_OPTION_STYLE" => "Y",
                     "CACHE_FILTER" => "N",
                     "CACHE_GROUPS" => "Y",
                     "CACHE_TIME" => "36000000",
                     "CACHE_TYPE" => "A",
                     "CHECK_DATES" => "Y",
                     "DETAIL_URL" => "",
                     "DISPLAY_BOTTOM_PAGER" => "Y",
                     "DISPLAY_DATE" => "N",
                     "DISPLAY_NAME" => "Y",
                     "DISPLAY_PICTURE" => "Y",
                     "DISPLAY_PREVIEW_TEXT" => "Y",
                     "DISPLAY_TOP_PAGER" => "N",
                     "FIELD_CODE" => array(
                         0 => "NAME",
                         1 => "PREVIEW_TEXT",
                         2 => "PREVIEW_PICTURE",
                         3 => "",
                     ),
                     "FILTER_NAME" => "",
                     "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                     "IBLOCK_ID" => "7",
                     "IBLOCK_TYPE" => "shops",
                     "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
                     "INCLUDE_SUBSECTIONS" => "Y",
                     "MESSAGE_404" => "",
                     "NEWS_COUNT" => "20",
                     "PAGER_BASE_LINK_ENABLE" => "N",
                     "PAGER_DESC_NUMBERING" => "N",
                     "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                     "PAGER_SHOW_ALL" => "N",
                     "PAGER_SHOW_ALWAYS" => "N",
                     "PAGER_TEMPLATE" => ".default",
                     "PAGER_TITLE" => "Новости",
                     "PARENT_SECTION" => "12",
                     "PARENT_SECTION_CODE" => "",
                     "PREVIEW_TRUNCATE_LEN" => "",
                     "PROPERTY_CODE" => array(
                         0 => "",
                         1 => "",
                     ),
                     "SET_BROWSER_TITLE" => "Y",
                     "SET_LAST_MODIFIED" => "N",
                     "SET_META_DESCRIPTION" => "Y",
                     "SET_META_KEYWORDS" => "Y",
                     "SET_STATUS_404" => "N",
                     "SET_TITLE" => "Y",
                     "SHOW_404" => "N",
                     "SORT_BY1" => "ACTIVE_FROM",
                     "SORT_BY2" => "SORT",
                     "SORT_ORDER1" => "DESC",
                     "SORT_ORDER2" => "ASC",
                     "STRICT_SECTION_CHECK" => "N",
                     "COMPONENT_TEMPLATE" => "shops"
                 ),
                 false
             );?>
             <h2 class="page-sub-title">Розничные отделы</h2>
             <?$APPLICATION->IncludeComponent(
                 "bitrix:news.list",
                 "shops",
                 array(
                     "ACTIVE_DATE_FORMAT" => "d.m.Y",
                     "ADD_SECTIONS_CHAIN" => "N",
                     "AJAX_MODE" => "N",
                     "AJAX_OPTION_ADDITIONAL" => "",
                     "AJAX_OPTION_HISTORY" => "N",
                     "AJAX_OPTION_JUMP" => "N",
                     "AJAX_OPTION_STYLE" => "Y",
                     "CACHE_FILTER" => "N",
                     "CACHE_GROUPS" => "Y",
                     "CACHE_TIME" => "36000000",
                     "CACHE_TYPE" => "A",
                     "CHECK_DATES" => "Y",
                     "DETAIL_URL" => "",
                     "DISPLAY_BOTTOM_PAGER" => "Y",
                     "DISPLAY_DATE" => "N",
                     "DISPLAY_NAME" => "Y",
                     "DISPLAY_PICTURE" => "Y",
                     "DISPLAY_PREVIEW_TEXT" => "Y",
                     "DISPLAY_TOP_PAGER" => "N",
                     "FIELD_CODE" => array(
                         0 => "NAME",
                         1 => "PREVIEW_TEXT",
                         2 => "PREVIEW_PICTURE",
                         3 => "",
                     ),
                     "FILTER_NAME" => "",
                     "HIDE_LINK_WHEN_NO_DETAIL" => "N",
                     "IBLOCK_ID" => "7",
                     "IBLOCK_TYPE" => "shops",
                     "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
                     "INCLUDE_SUBSECTIONS" => "Y",
                     "MESSAGE_404" => "",
                     "NEWS_COUNT" => "20",
                     "PAGER_BASE_LINK_ENABLE" => "N",
                     "PAGER_DESC_NUMBERING" => "N",
                     "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                     "PAGER_SHOW_ALL" => "N",
                     "PAGER_SHOW_ALWAYS" => "N",
                     "PAGER_TEMPLATE" => ".default",
                     "PAGER_TITLE" => "Новости",
                     "PARENT_SECTION" => "13",
                     "PARENT_SECTION_CODE" => "",
                     "PREVIEW_TRUNCATE_LEN" => "",
                     "PROPERTY_CODE" => array(
                         0 => "",
                         1 => "",
                     ),
                     "SET_BROWSER_TITLE" => "Y",
                     "SET_LAST_MODIFIED" => "N",
                     "SET_META_DESCRIPTION" => "Y",
                     "SET_META_KEYWORDS" => "Y",
                     "SET_STATUS_404" => "N",
                     "SET_TITLE" => "Y",
                     "SHOW_404" => "N",
                     "SORT_BY1" => "ACTIVE_FROM",
                     "SORT_BY2" => "SORT",
                     "SORT_ORDER1" => "DESC",
                     "SORT_ORDER2" => "ASC",
                     "STRICT_SECTION_CHECK" => "N",
                     "COMPONENT_TEMPLATE" => "shops"
                 ),
                 false
             );?>
		 <?endif;?>
	</div>
</div>
 <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>